name: evaluation
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - jupyterlab
  - nbstripout
  - numpy
  - openbabel
  - pandas
  - plotly
  - posebusters
  - pytest
  - python=3.11
  - pytorch
  - rdkit
  - ruff
  - scipy
  - seaborn
  - tqdm
  - pip:
      - git+https://github.com/hesther/espsim.git
