name: evaluation
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - jupyterlab
  - pandas
  - plotly
  - posebusters
  - pytest
  - python=3.11
  - pytorch
  - rdkit
  - ruff
  - seaborn
