name: evaluation
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - jupyterlab
  - nbstripout
  - numpy>=2
  - openbabel
  - pandas>=2
  - pip
  - plotly
  - posebusters
  - pytest
  - python=3.11
  - pytorch
  - rdkit==2024.03
  - rich
  - ruff
  - scipy
  - seaborn
  - tqdm
  - pip:
      - git+https://github.com/hesther/espsim.git
