name: evaluation
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - bokeh
  - colorcet
  - datashader
  - holoviews
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - nbstripout
  - numpy>=2
  - openbabel
  - pandas>=2
  - pip
  - plotly
  - posebusters
  - pytest
  - python-kaleido
  - python=3.11
  - pytorch
  - rdkit>=2024.09.5
  - rich
  - ruff
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - umap-learn
  - pip:
      - git+https://github.com/hesther/espsim.git
